title: Zachary Espiritu
email: me@zacharyespiritu.com
description: I'm a high school developer looking to create. Creator of Tile, Tap, Push!, Reaction Line, and Math Battle II.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zacharyespiritu.com" # the base hostname & protocol for your site

twitter:
  username: ZacharyEspiritu
github_username: ZacharyEspiritu

markdown: rdiscount

timezone: America/New_York

permalink: /blog/:slug/

# Build settings
markdown: kramdown
theme: minima

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /project/:title/
  designs:
    output: true
    permalink: /design/:title/

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  -
    scope:
      path: ""      # empty string for all files
      type: projects   # limit to posts
    values:
      is_project: true # automatically set is_post=true for all posts
