title: Zachary Espiritu
email: me@zacharyespiritu.com
description: >
  I'm a software engineer and lighting designer. Named one of 10Under20 @ CEWeek
  2016. Developer of Math Battle, Tile, Tap, Push!, and Reaction Line.
baseurl: ""
url: "http://zacharyespiritu.com"

markdown: kramdown

timezone: America/New_York

twitter:
  username: ZacharyEspiritu
github_username: ZacharyEspiritu

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /project/:title/
  designs:
    output: true
    permalink: /design/:title/
  posts:
    output: true
    permalink: /blog/:slug/

defaults:
  - scope:
      path: ""
    values:
      image:
        path: /images/social-banner.png
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
  - scope:
      path: ""
      type: projects
    values:
      is_project: true
